package UI;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class ToBeEncryptedOrDecrypted extends javax.swing.JFrame
{

    private File[] listOfFilesAndFolders;
    private String encryptOrDecrypt;
    
    public ToBeEncryptedOrDecrypted(File[] listOfFilesAndFolders, String encryptOrDecrypt)
    {
        this.listOfFilesAndFolders = listOfFilesAndFolders;
        this.encryptOrDecrypt = encryptOrDecrypt;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ToBeEncryptedOrDecrypted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ToBeEncryptedOrDecrypted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ToBeEncryptedOrDecrypted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ToBeEncryptedOrDecrypted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        initComponents();
        setResizable(false);
        listOfFilesAndFoldersTextField.setEditable(false);
        
        if(encryptOrDecrypt.equalsIgnoreCase("encrypt"))
        {
            encryptOrDecryptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lock.png")));
            //jLabel3.setForeground(new java.awt.Color(255, 51, 51));
            encryptOrDecryptButton.setBackground(new java.awt.Color(255, 51, 51));
            jLabel3.setText("Encrypt");
            heading.setText("Files to be encryped:");
        }
        else if(encryptOrDecrypt.equalsIgnoreCase("decrypt"))
        {
            encryptOrDecryptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/unlock.png")));
            //jLabel3.setForeground(new java.awt.Color(102,255,102));
            encryptOrDecryptButton.setBackground(new java.awt.Color(102,255,102));
            jLabel3.setText("Decrypt");
            heading.setText("Files to be decryped:");
        }
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener( new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                JFrame frame = (JFrame)e.getSource();
                Toolkit.getDefaultToolkit().beep();
                int result = JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit the application?", "Exit Application", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION)
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
        
        displayListOfFilesInTheTextField();
        getRootPane().setDefaultButton(encryptOrDecryptButton);
        
    }
    
    private void displayListOfFilesInTheTextField()
    {
        for(Integer i=0, j=1; i < listOfFilesAndFolders.length; i++, j++)
        {
            listOfFilesAndFoldersTextField.append(j.toString()+". "+listOfFilesAndFolders[i].getName()+"\n");
            listOfFilesAndFoldersTextField.append(listOfFilesAndFolders[i].getAbsolutePath()+"\n\n");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfFilesAndFoldersTextField = new javax.swing.JTextArea();
        reSelectFilesButton = new javax.swing.JButton();
        addMoreFilesButton = new javax.swing.JButton();
        encryptOrDecryptButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Files to be encryped:");

        listOfFilesAndFoldersTextField.setBackground(new java.awt.Color(153, 153, 153));
        listOfFilesAndFoldersTextField.setColumns(20);
        listOfFilesAndFoldersTextField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        listOfFilesAndFoldersTextField.setRows(5);
        jScrollPane1.setViewportView(listOfFilesAndFoldersTextField);

        reSelectFilesButton.setBackground(new java.awt.Color(153, 153, 153));
        reSelectFilesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/re.png"))); // NOI18N
        reSelectFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reSelectFilesButtonActionPerformed(evt);
            }
        });

        addMoreFilesButton.setBackground(new java.awt.Color(153, 153, 153));
        addMoreFilesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        addMoreFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreFilesButtonActionPerformed(evt);
            }
        });

        encryptOrDecryptButton.setBackground(new java.awt.Color(102, 255, 102));
        encryptOrDecryptButton.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        encryptOrDecryptButton.setMaximumSize(new java.awt.Dimension(97, 73));
        encryptOrDecryptButton.setMinimumSize(new java.awt.Dimension(97, 73));
        encryptOrDecryptButton.setName(""); // NOI18N
        encryptOrDecryptButton.setPreferredSize(new java.awt.Dimension(97, 73));
        encryptOrDecryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptOrDecryptButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add More Files");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reselect All");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addMoreFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(encryptOrDecryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reSelectFilesButton))
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMoreFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reSelectFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encryptOrDecryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMoreFilesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addMoreFilesButtonActionPerformed
    {//GEN-HEADEREND:event_addMoreFilesButtonActionPerformed
        
        for(File file:listOfFilesAndFolders)
        {
            System.out.println(file);
        }
        
        new FileChooser(encryptOrDecrypt, listOfFilesAndFolders).setVisible(true);
        dispose();
    }//GEN-LAST:event_addMoreFilesButtonActionPerformed

    private void encryptOrDecryptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encryptOrDecryptButtonActionPerformed
    {//GEN-HEADEREND:event_encryptOrDecryptButtonActionPerformed
        setVisible(false);
        dispose();
        if(encryptOrDecrypt.equalsIgnoreCase("encrypt"))
        {
            new PasswordTakerForEncryption(listOfFilesAndFolders).setVisible(true);
        }
        else if(encryptOrDecrypt.equalsIgnoreCase("decrypt"))
        {
            new PasswordTakerForDecryption(listOfFilesAndFolders).setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_encryptOrDecryptButtonActionPerformed

    private void reSelectFilesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_reSelectFilesButtonActionPerformed
    {//GEN-HEADEREND:event_reSelectFilesButtonActionPerformed
        new FileChooser(encryptOrDecrypt).setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_reSelectFilesButtonActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoreFilesButton;
    private javax.swing.JButton encryptOrDecryptButton;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listOfFilesAndFoldersTextField;
    private javax.swing.JButton reSelectFilesButton;
    // End of variables declaration//GEN-END:variables
}
